---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    requirements-file: ../../requirements.yml
driver:
  name: docker
platforms:
  - name: storage-test
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: ""
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    exposed_ports:
      - 9000/tcp
      - 9001/tcp
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    host_vars:
      storage-test:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      host_key_checking: false
      retry_files_enabled: false
verifier:
  name: ansible
  options:
    show-diff: true
