---
- name: Prepare test environment
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Mock Vault token for testing
      ansible.builtin.set_fact:
        vault_token_mock: "test-token-12345"
        tailscale_authkey: "tskey-test-mock-key-12345"

