---
- name: Prepare test environment for ISO builder
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Create mock Proxmox repo files (simulate Proxmox environment)
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/pve-enterprise.list
        content: |
          # Mock enterprise repo for testing
          # deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
        owner: root
        group: root
        mode: "0644"
